### ISSUE TITLE
Any plans to support "scheduled" operators, like .debounce?

### ISSUE THREAD

**Issue by mincequi** [tcbrindle/flux#131]
Hi there
and thanks for you effort to create this nice lib. Are there actually any plans to support "scheduled" operator like debounce, throttle, delay? Or maybe smoothing operators like median or exponential moving average?

Thanks already.

Best regards
Manuel

**Comment by tcbrindle** [comment]
Hi @mincequi, I'm afraid I'm not familiar with the "scheduled" operators you mention. Do you have a link to some documentation for another library/language that offers these so I can get an idea of what they do?

**Comment by mincequi** [comment]
Hi @tcbrindle,
I can share some information regarding that. Since I am currently developing in kotlin, there is Kotlin Flow:
https://kotlinlang.org/docs/flow.html

And here is the debounce operator for example:
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html

Hope that helps/gets you an idea, what the fuzz is about :)

Thanks already.

**Comment by tcbrindle** [comment]
Hi @mincequi, sorry for the delay replying to you!

From reading the documentation then Flux is equivalent to Kotlin's synchronous [Sequences](https://kotlinlang.org/docs/sequences.html) rather than its asynchronous, coroutine-based flows. I'd be happy to look at adding equivalents to Kotlin's sequence functions if you think we're missing any, but I think the async "flow" stuff is out of scope for this library I'm afraid.
