### ISSUE TITLE
Clang crash

### ISSUE THREAD

**Issue by ahdnm** [tcbrindle/flux#179]
Similar to the issue #174, this code also causes clang to crash https://flux.godbolt.org/z/3fT4r548j

**Comment by tcbrindle** [comment]
Hi @ahdnm, thanks for the report. I've added it to Clang issue: https://github.com/llvm/llvm-project/issues/85148

Meanwhile, it looks like I'll have to come up with a better workaround than #175

**Comment by tcbrindle** [comment]
Hi @ahdnm, it looks like this bug was fixed in Clang 18.1.3 (https://github.com/llvm/llvm-project/issues/86769). 

I've tested locally with 18.1.4 and this example now compiles as expected. Testing with Clang trunk on Compiler Explorer seems to work as well: https://flux.godbolt.org/z/bb8dcsqY8 (CE doesn't have any 18.1 point releases).

So hopefully this is now sorted, but if you have any more problems please let me know :)
